/**
 * Add a custom Simple API entry (rawdata/addmanual) at the end of the list, then disable it.
 *
 * Usage (from lib/node):
 *   npm run add-simple-api
 *
 * Env:
 *   RACERESULT_API_KEY (required)
 *   RACERESULT_API_URL (optional, default events.raceresult.com)
 *   EVENT_ID (optional, default 410827)
 *   SIMPLE_API_LABEL (optional, default "Custom addmanual test")
 */

import { RaceResultApi } from '../src';
import { SimpleAPIItem } from '../src/types';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../../../.env') });

const EVENT_ID = process.env.EVENT_ID || '410827';
const SIMPLE_API_URL = 'rawdata/addmanual';
const SIMPLE_API_LABEL = process.env.SIMPLE_API_LABEL || 'Custom addmanual test';

function printSimpleApiList(title: string, items: SimpleAPIItem[]): void {
  console.log(`\n${title} (${items.length} entries)`);
  console.log('-'.repeat(80));
  if (items.length === 0) {
    console.log('  (empty)');
    return;
  }
  items.forEach((item, index) => {
    const status = item.Disabled ? 'disabled' : 'active';
    const label = item.Label || '(no label)';
    console.log(
      `  ${String(index + 1).padStart(2)}. [${status}] ${item.URL} | ${label} | Key: ${item.Key}`
    );
  });
  console.log('-'.repeat(80));
}

function printPostmanCredentials(server: string, eventId: string, sessionId: string): void {
  const base = `https://${server}`;
  console.log('\n=== Postman credentials ===');
  console.log('\n1) Login');
  console.log(`   POST ${base}/api/public/login`);
  console.log('   Body: x-www-form-urlencoded');
  console.log('         apikey = <RACERESULT_API_KEY from .env>');
  console.log('   Response body = session token (use as Bearer below)');
  console.log('\n2) Bearer token (copy for all event API calls)');
  console.log(`   Authorization: Bearer ${sessionId}`);
  console.log('\n3) List Simple API entries');
  console.log(`   GET ${base}/_${eventId}/api/simpleapi/get`);
  console.log(`   Header: Authorization: Bearer ${sessionId}`);
  console.log('\n4) Save all Simple API entries (append flow)');
  console.log(`   POST ${base}/_${eventId}/api/simpleapi/saveall`);
  console.log(`   Header: Authorization: Bearer ${sessionId}`);
  console.log('         Content-Type: application/json');
  console.log('   Body: JSON array of { Disabled, Key, URL, Label }');
  console.log('         (full list from step 3 + your new entry appended)');
  console.log('===========================\n');
}

async function main() {
  const apiKey = process.env.RACERESULT_API_KEY;
  if (!apiKey || apiKey === 'your_api_key_here') {
    console.error('Set RACERESULT_API_KEY in .env');
    process.exit(1);
  }

  const server = process.env.RACERESULT_API_URL || 'events.raceresult.com';
  const api = new RaceResultApi({
    server,
    https: true,
    userAgent: 'node-add-simple-api/1.0',
  });

  try {
    console.log(`Server: ${server}`);
    console.log(`Event:  ${EVENT_ID}`);
    console.log('Logging in...');
    await api.public().login({ apiKey });
    const sessionId = api.getSessionId();
    console.log(`Login OK`);
    printPostmanCredentials(server, EVENT_ID, sessionId);

    const ea = api.eventApi(EVENT_ID);

    console.log('\nGET simpleapi/get ...');
    const before = await ea.simpleApi().get();
    console.log('Read OK');
    printSimpleApiList('Simple API list BEFORE add', before);

    const newItem = {
      Key: '',
      URL: SIMPLE_API_URL,
      Label: SIMPLE_API_LABEL,
      Disabled: false,
    };
    console.log('\nNew entry to append (Key will be auto-generated if empty):');
    console.log(JSON.stringify({ ...newItem, Key: '<auto-generated 32 chars>' }, null, 2));
    console.log(`\nPOST simpleapi/saveall body will contain ${before.length + 1} items`);

    console.log(`\nPOST simpleapi/saveall (append ${SIMPLE_API_URL}) ...`);
    const entry = await ea.simpleApi().appendEndpoint({
      url: SIMPLE_API_URL,
      label: SIMPLE_API_LABEL,
    });
    console.log('Save OK');

    console.log('\nGET simpleapi/get (verify) ...');
    const after = await ea.simpleApi().get();
    console.log('Read OK');
    printSimpleApiList('Simple API list AFTER add', after);

    console.log('\nAdded entry:');
    console.log(`  Key:      ${entry.Key}`);
    console.log(`  URL:      ${entry.URL}`);
    console.log(`  Label:    ${entry.Label}`);
    console.log(`  Disabled: ${entry.Disabled}`);
    console.log(`  Public:   https://api.raceresult.com/${EVENT_ID}/${entry.Key}/${entry.URL}`);

    const addedIndex = after.findIndex((item) => item.Key === entry.Key);
    if (addedIndex === -1) {
      throw new Error(`Added entry not found in list (Key: ${entry.Key})`);
    }

    console.log(`\nPOST simpleapi/saveall (disable index ${addedIndex}) ...`);
    const disabled = await ea.simpleApi().disableEndpoints([addedIndex]);
    console.log('Disable OK');

    console.log('\nGET simpleapi/get (verify disable) ...');
    const afterDisable = await ea.simpleApi().get();
    console.log('Read OK');
    printSimpleApiList('Simple API list AFTER disable', afterDisable);

    const disabledEntry = disabled[addedIndex];
    console.log('\nDisabled entry:');
    console.log(`  Index:    ${addedIndex}`);
    console.log(`  Key:      ${disabledEntry.Key}`);
    console.log(`  URL:      ${disabledEntry.URL}`);
    console.log(`  Label:    ${disabledEntry.Label}`);
    console.log(`  Disabled: ${disabledEntry.Disabled}`);

    console.log('\nPostman save example (new entry only):');
    console.log(JSON.stringify(entry, null, 2));
  } catch (error: any) {
    console.error('\nError:', error.message);
    if (error.status) {
      console.error(`Status: ${error.status}`);
    }
    process.exit(1);
  } finally {
    console.log('\nLogging out...');
    await api.public().logout();
    console.log('Done.');
  }
}

if (require.main === module) {
  main();
}
